---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: Copy sources.list
    ansible.builtin.copy:
      src: etc/apt/sources.list
      dest: /etc/apt/sources.list
      owner: root
      group: root

  - name: Update system
    ansible.builtin.apt:
      update_cache: yes

  - name: Install packages
    ansible.builtin.apt:
      pkg:
      - htop
      - curl
      - python3-psutil
      - qbittorrent
      - snapd
      - timeshift
      - ksystemlog
      - zsh
      - flatpak
      - nvidia-driver
      - webcamoid


  - name: Add Brave Browser repo key
    become: true
    shell: curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

  - name: Copy Brave Browser GPG file
    shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" > /etc/apt/sources.list.d/brave-browser-release.list   

  - name: Update system
    ansible.builtin.apt:
      update_cache: yes

  - name: Copy .bashrc config file
    ansible.builtin.copy:
      src: .dotfiles/bashrc
      dest: /home/filip/.bashrc
      owner: filip
      group: filip

  - name: Copy bashrc keybindings file
    ansible.builtin.copy:
      src: .dotfiles/inputrc
      dest: /etc/inputrc
      owner: root
      group: root

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Install Brave Browser
    become: true
    ansible.builtin.apt:
      name: brave-browser
      state: present

  - name: Install snap packages
    community.general.snap:
      name: "{{ item.name }}"
      classic: "{{ item.classic | default(false) }}"
      state: present
    loop:
      - name: whatsdesk
      - name: spotify
      - name: powershell
        classic: true
      - name: code
        classic: true

  - name: Fetch snap package desktop files
    become: true
    find:
      paths: /var/lib/snapd/desktop/applications/
      patterns: "*.desktop"
    register: snap_files

  - name: Copy snap packages to show in app launcher
    become: true
    fetch:
      src: "{{ item.path }}"
      dest: /usr/share/applications
      owner: root
      group: root
    loop: "{{ snap_files.files }}"

  - name: Remove packages
    ansible.builtin.package:
      name:
        - kalendarac
        - kmail
        - kmailtransport-akonadi
        - korganizer
        - knotes
        - kdepim-themeeditors
        - konqueror
        - juk
        - dragonplayer
        - libreoffice
        - firefox-esr
      state: absent

  - name: Remove dependencies that are no longer required and purge their configuration files
    ansible.builtin.apt:
      autoremove: yes
      purge: true

  - name: Configure nvidia power management
    shell: echo "options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp" > /etc/modprobe.d/nvidia-power-management.conf

  - name: Install ZeroTier
    ansible.builtin.command: curl -s https://install.zerotier.com | sudo bash

  - name: Add flathub remote if not exists
    ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  - name: Install FlatPak packages
    become: true
    community.general.flatpak:
      name:
        - org.libreoffice.LibreOffice
        - org.mozilla.firefox
        - org.videolan.VLC

  - name: Download TeamViewer
    ansible.builtin.get_url:
      url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
      dest: /home/filip/Downloads

  - name: Install TeamViewer
    become: true
    delegate_to: teamviewer
    ansible.builtin.apt:
      deb: /home/filip/Downloads/teamviewer_15.51.5_amd64.deb

  - name: Configure plasma 1
    become: true
    ansible.builtin.copy:
      src: .dotfiles/.config/plasma-org.kde.plasma.desktop-appletsrc
      dest: /home/filip/.config/plasma-org.kde.plasma.desktop-appletsrc
      owner: filip
      group: filip

  - name: configure Plasma 2
    become: true
    ansible.builtin.copy:
      src: .dotfiles/.config/kdeglobals
      dest: /home/filip/.config/kdeglobals
      owner: filip
      group: filip

  - name: Configure Plasma 3
    become: true
    ansible.builtin.copy:
      src: .dotfiles/.config/xsettingsd/xsettingsd.conf
      dest: /home/filip/.config/xsettingsd/xsettingsd.conf
      owner: filip
      group: filip

  - name: Copy kwinrc - night colour
    become: true
    ansible.builtin.copy:
      src: .dotfiles/.config/kwinrc
      dest: /home/filip/.config/kwinrc
      owner: filip
      group: filip

  - name: Copy konsolerc
    become_user: filip
    ansible.builtin.copy:
      src: .dotfiles/.config/konsolerc
      dest: /home/filip/.config/konsolerc
      owner: filip
      group: filip

  - name: Copy mimeapps.list
    ansible.builtin.copy:
      src: .dotfiles/.config/mimeapps.list
      dest: /home/filip/.config/mimeapps.list
      owner: filip
      group: filip

  - name: Copy lock screen duration settings
    ansible.builtin.copy:
      src: .dotfiles/.config/kdedefaults/kscreenlockerrc
      dest: /home/filip/.config/kdedefaults/kscreenlockerrc
      owner: filip
      group: filip

  - name: Copy spectacle config
    become: true
    ansible.builtin.copy:
      src: .dotfiles/spectacle
      dest: /home/filip/s
      owner: root
      group: root

  - name: Copy nanorc config
    ansible.builtin.copy:
      src: .dotfiles/nanorc
      dest: /home/filip/.nanorc
      owner: root
      group: root

  - name: Create script directory /home/filip/bin
  ansible.builtin.file:
    path: /home/filip/bin
    state: directory

  - name: Copy update script
    ansible.builtin.copy:
      src: .dotfiles/update.sh
      dest: /home/filip/bin/update.s  h
    owner: fili p
    group: fili p
