---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Remove packages
    ansible.builtin.package:
      name:
        - kcalc
        - kwalletmanager
        - kedconnect
        - kalendarac
        - kmail
        - kmailtransport-akonadi
        - korganizer
        - knotes
        - kdepim-themeeditors
        - konqueror
        - juk
        - dragonplayer
        - libreoffice
        - firefox-esr
      state: absent

  - name: Remove dependencies that are no longer required and purge their configuration files
    ansible.builtin.apt:
      autoremove: yes
      purge: true

  - name: Copy sources.list
    ansible.builtin.copy:
      src: etc/apt/sources.list
      dest: /etc/apt/sources.list
      owner: root
      group: root

  - name: Add Brave Browser repo key
    become: true
    shell: curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

  - name: Copy Brave Browser GPG file
    shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" > /etc/apt/sources.list.d/brave-browser-release.list   

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Install packages
    ansible.builtin.apt:
      pkg:
      - htop
      - tmux
      - neofetch
      - curl
      - python3-psutil
      - timeshift
      - ksystemlog
      - zsh
      - flatpak
      - webcamoid
      - adb
      - net-tools
      - locate

  - name: Copy .bashrc config file
    ansible.builtin.copy:
      src: .dotfiles/.bashrc
      dest: "{{ lookup('env', 'HOME') }}/.bashrc"
      owner: filip
      group: filip

  - name: Copy bashrc keybindings file
    ansible.builtin.copy:
      src: .dotfiles/.inputrc
      dest: "{{ lookup('env', 'HOME') }}/.inputrc"
      owner: filip
      group: filip

  - name: Install Brave Browser
    become: true
    ansible.builtin.apt:
      name: brave-browser
      state: present

  - name: Configure nvidia power management
    ansible.builtin.shell: echo "options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp" > /etc/modprobe.d/nvidia-power-management.conf

  - name: Install ZeroTier
    ansible.builtin.shell: curl -s https://install.zerotier.com | sudo bash

  - name: Add flathub remote if not exists
    ansible.builtin.shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  - name: Install FlatPak packages
    become: true
    community.general.flatpak:
      name:
        - org.onlyoffice.desktopeditors
        - org.mozilla.firefox
        - org.videolan.VLC
        - uk.org.greenend.chiark.sgtatham.putty
        - org.kde.kcalc
        - io.github.mimbrero.WhatsAppDesktop
        - org.freedesktop.Platform.GL.nvidia-525-147-05
        - org.qbittorrent.qBittorrent
      state: present

  - name: Download TeamViewer
    ansible.builtin.get_url:
      url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
      dest: "/tmp/teamviewer.deb"
    become: no

  - name: Install TeamViewer
    ansible.builtin.shell: dpkg -i "/tmp/teamviewer.deb"

  - name: Download Visual Studio Code
    ansible.builtin.get_url:
      url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
      dest: "/tmp/code.deb"
    become: no

  - name: Install Visual Studio Code
    ansible.builtin.shell: dpkg -i "/tmp/code.deb"

  - name: Configure plasma 1
    become: true
    ansible.builtin.copy:
      src: .dotfiles/.config/plasma-org.kde.plasma.desktop-appletsrc
      dest: "{{ lookup('env', 'HOME') }}/.config/plasma-org.kde.plasma.desktop-appletsrc"
      owner: filip
      group: filip

  - name: configure Plasma 2
    become: true
    ansible.builtin.copy:
      src: .dotfiles/.config/kdeglobals
      dest: "{{ lookup('env', 'HOME') }}/.config/kdeglobals"
      owner: filip
      group: filip

  - name: Configure Plasma 3
    become: true
    ansible.builtin.copy:
      src: .dotfiles/.config/xsettingsd/xsettingsd.conf
      dest: "{{ lookup('env', 'HOME') }}/.config/xsettingsd/xsettingsd.conf"
      owner: filip
      group: filip

  - name: Copy kwinrc - night colour
    become: true
    ansible.builtin.copy:
      src: .dotfiles/.config/kwinrc
      dest: "{{ lookup('env', 'HOME') }}/.config/kwinrc"
      owner: filip
      group: filip

  - name: Copy konsolerc
    ansible.builtin.copy:
      src: .dotfiles/.config/konsolerc
      dest: "{{ lookup('env', 'HOME') }}/.config/konsolerc"
      owner: filip
      group: filip

  - name: Copy mimeapps.list
    ansible.builtin.copy:
      src: .dotfiles/.config/mimeapps.list
      dest: "{{ lookup('env', 'HOME') }}/.config/mimeapps.list"
      owner: filip
      group: filip

  - name: Copy lock screen duration settings
    ansible.builtin.copy:
      src: .dotfiles/.config/kdedefaults/kscreenlockerrc
      dest: "{{ lookup('env', 'HOME') }}/.config/kdedefaults/kscreenlockerrc"
      owner: filip
      group: filip

  - name: Copy spectacle config
    ansible.builtin.copy:
      src: .dotfiles/.config/spectaclerc
      dest: "{{ lookup('env', 'HOME') }}/.config/spectaclerc"
      owner: filip
      group: filip

  - name: Copy nanorc config
    ansible.builtin.copy:
      src: .dotfiles/.nanorc
      dest: "{{ lookup('env', 'HOME') }}/.nanorc"
      owner: filip
      group: filip

  - name: Create script directory {{ lookup('env', 'HOME') }}/bin
    ansible.builtin.file:
      path: "{{ lookup('env', 'HOME') }}/bin"
      state: directory

  - name: Copy scripts
    ansible.builtin.copy:
      src: files/scripts/
      dest: "{{ lookup('env', 'HOME') }}/bin/"
      owner: filip
      group: filip

  - name: Set execution permissions for files in scripts folder
    ansible.builtin.file:
      path: "{{ lookup('env', 'HOME') }}/bin"
      mode: u+x
      recurse: yes

  - name: Clean up Downloads folder
    ansible.builtin.file:
      path: "{{ lookup('env', 'HOME') }}/Downloads/*"
      state: absent
