---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Remove packages
    ansible.builtin.package:
      name:
        - kcalc
        - kwalletmanager
        - kdeconnect
        - kalendarac
        - kmail
        - kmailtransport-akonadi
        - korganizer
        - knotes
        - kmouth
        - kdepim-themeeditors
        - konqueror
        - juk
        - dragonplayer
        - firefox-esr
      state: absent

  - name: Purge Liberty
    become: true
    shell: apt purge "libreoffice*" -y

  - name: Remove and purge dependencies
    ansible.builtin.apt:
      autoremove: yes
      purge: true

  - name: Copy sources.list
    ansible.builtin.copy:
      src: etc/apt/sources.list
      dest: /etc/apt/sources.list
      owner: root
      group: root

  - name: Add Brave Browser repo key
    become: true
    shell: curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

  - name: Copy Brave Browser GPG file
    shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" > /etc/apt/sources.list.d/brave-browser-release.list

  - name: Add Signal signing key 1
    become: true
    shell: wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg

  - name: Add Signal signing key 2
    become: true
    shell: cat signal-desktop-keyring.gpg | sudo tee /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null

  - name: Add Signal repo
    become: true
    shell: echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' |\  sudo tee /etc/apt/sources.list.d/signal-xenial.list

  - name: Update apt
    ansible.builtin.apt:
      update_cache: yes

  - name: upgrade system
    ansible.builtin.apt:
      upgrade: dist

  - name: Install packages
    ansible.builtin.apt:
      pkg:
      - htop
      - tmux
      - neofetch
      - python3-psutil
      - timeshift
      - ksystemlog
      - latpak
      - webcamoid
      - adb
      - net-tools
      - network-manager
      - locate
      - tldr
      - tree
      - iperf
      - brave-browser
      - signal-desktop

  - name: Copy .bashrc config file
    ansible.builtin.copy:
      src: .dotfiles/.bashrc
      dest: "/home/filip/.bashrc"
      owner: filip
      group: filip

  - name: Copy bashrc keybindings file
    ansible.builtin.copy:
      src: .dotfiles/.inputrc
      dest: "/home/filip/.inputrc"
      owner: filip
      group: filip

  - name: Configure nvidia power management
    ansible.builtin.shell: echo "options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp" > /etc/modprobe.d/nvidia-power-management.conf

  - name: Add flathub remote if not exists
    ansible.builtin.shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  - name: Install FlatPak packages
    become: true
    community.general.flatpak:
      name:
        - org.onlyoffice.desktopeditors
        - io.gitlab.librewolf-community
        - org.videolan.VLC
        - org.kde.kcalc
        - org.freedesktop.Platform.GL.nvidia-535-183-01
        - org.qbittorrent.qBittorrent
      state: present

  - name: Download TeamViewer
    ansible.builtin.get_url:
      url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
      dest: "/tmp/teamviewer.deb"

  - name: Install TeamViewer
    become: true
    ansible.builtin.shell: dpkg -i "/tmp/teamviewer.deb"

  - name: Download Visual Studio Code
    ansible.builtin.get_url:
      url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
      dest: "/tmp/code.deb"

  - name: Install Visual Studio Code
    ansible.builtin.shell: dpkg -i "/tmp/code.deb"

  - name: Configure plasma 1
    become: true
    ansible.builtin.copy:
      src: .dotfiles/.config/plasma-org.kde.plasma.desktop-appletsrc
      dest: "/home/filip/.config/plasma-org.kde.plasma.desktop-appletsrc"
      owner: filip
      group: filip

  - name: configure Plasma 2
    become: true
    ansible.builtin.copy:
      src: .dotfiles/.config/kdeglobals
      dest: "/home/filip/.config/kdeglobals"
      owner: filip
      group: filip

  - name: Configure Plasma 3
    become: true
    ansible.builtin.copy:
      src: .dotfiles/.config/xsettingsd/xsettingsd.conf
      dest: "/home/filip/.config/xsettingsd/xsettingsd.conf"
      owner: filip
      group: filip

  - name: Copy kwinrc - night colour
    become: true
    ansible.builtin.copy:
      src: .dotfiles/.config/kwinrc
      dest: "/home/filip/.config/kwinrc"
      owner: filip
      group: filip

  - name: Copy konsolerc
    ansible.builtin.copy:
      src: .dotfiles/.config/konsolerc
      dest: "/home/filip/.config/konsolerc"
      owner: filip
      group: filip

  - name: Copy mimeapps.list
    ansible.builtin.copy:
      src: .dotfiles/.config/mimeapps.list
      dest: "/home/filip/.config/mimeapps.list"
      owner: filip
      group: filip

  - name: Copy lock screen duration settings
    ansible.builtin.copy:
      src: .dotfiles/.config/kdedefaults/kscreenlockerrc
      dest: "/home/filip/.config/kdedefaults/kscreenlockerrc"
      owner: filip
      group: filip

  - name: Copy spectacle config
    ansible.builtin.copy:
      src: .dotfiles/.config/spectaclerc
      dest: "/home/filip/.config/spectaclerc"
      owner: filip
      group: filip

  - name: Copy nanorc config
    ansible.builtin.copy:
      src: .dotfiles/.nanorc
      dest: "/home/filip/.nanorc"
      owner: filip
      group: filip

  - name: Create script directory /home/filip/bin
    ansible.builtin.file:
      path: "/usr/local/bin"
      state: directory

  - name: Copy scripts
    ansible.builtin.copy:
      src: files/scripts/
      dest: "/usr/local/bin/"
      owner: filip
      group: filip

  - name: Set execution permissions for files in scripts folder
    ansible.builtin.file:
      path: "/usr/local/bin"
      mode: u+x
      recurse: yes
