---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: nvidia-drivers
      name: curl
      name: snapd
      name: python3-psutils
      name: htop
      name: vlc
      name: timeshift
      name: Ksystemlog
      name: brave-browser
      name: qbittorrent
      name: teamviewer
      name: zsh
      name: flatpak

  - name: copy Brave browser files
    copy:
      src: files/Brave-Browser
      dst: ~/.config/Brave-Browser
      owner: root
      group: root
