---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/filip/.bashrc
      owner: filip
      group: filip

  - name: copy bashrc keybindings
    copy:
      src: files/inputrc
      dest: /etc/inputrc
      owner: root
      group: root

  - name: copy sources.list
    copy:
      src: files/sources.list
      dest: /etc/apt/sources.list
      owner: root
      group: root

  - name: Add brave browser repository key
    become: true
    shell: curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

  - name: copy brave repo file
    copy:
      src: files/brave-browser-release.list
      dest: /etc/apt/sources.list.d/brave-browser-release.list
      owner: filip
      group: filip

  - name: update apt cache
    become: true
    apt: update_cache=yes

  - name: install brave browser
    become: true
    apt:
      name: brave-browser
      state: present

  - name: install spotify
    become: true
    community.general.snap:
      name: spotify
      state: present

  - name: install
    community.general.snap:
      name: "{{ item.name }}"
      classic: "{{ item.classic| default(false) }}"
      state: present
    loop:
      - name: whatsdesk
      - name: powershell
        classic: true
      - name: code
        classic: true

  - name: find all snap package desktop file
    become: true
    find:
      paths: /var/lib/snapd/desktop/applications/
      patterns: "*.desktop"
    register: snap_files

  - name: copy snap package desktop files
    become: true
    fetch:
      src: "{{ item.path }}"
      dest: /usr/share/applications
      owner: root
      group: root
    loop: "{{ snap_files.files }}"

  - name: install packages
    package:
      name: "{{ item }}"
      state: present
    loop:
      - htop
      - curl
      - python3-psutil
      - qbittorrent
      - nvidia-driver
      - snapd
      - timeshift
      - ksystemlog
      - zsh
      - flatpak
      - putty

#  - name: install vlc
#    become_user: filip
#    flatpak:
#      name: org.videolan.VLC
#      method: user
#      state: present

  - name: download teamviewer
    ansible.builtin.get_url:
      url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
      dest: /home/filip/Downloads

  - name: install teamviewer
    become: true
    delegate_to: teamviewer
    apt:
      deb: /home/filip/Downloads/teamviewer_15.51.5_amd64.deb

  - name: configure plasma
    become: true
    copy:
      src: files/plasma-org.kde.plasma.desktop-appletsrc
      dest: /home/filip/.config/plasma-org.kde.plasma.desktop-appletsrc
      owner: root
      group: root

  - name: configure plasma
    become: true
    copy:
      src: files/kdeglobals
      dest: /home/filip/.config/kdeglobals
      owner: root
      group: root

  - name: configure plasma
    become: true
    copy:
      src: files/xsettingsd.conf
      dest: /home/filip/.config/xsettingsd/xsettings.conf
      owner: root
      group: root
