---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: copy sources.list
    copy:
      src: files/sources.list
      dest: /etc/apt/sources.list
      owner: root
      group: root

  - name: Update apt cache
    become: true
    apt:
      update_cache: yes

  - name: install packages
    package:
      name: "{{ item }}"
      state: present
    loop:
      - htop
      - curl
      - python3-psutil
      - vlc
      - qbittorrent
      - nvidia-driver
      - snapd
      - timeshift
      - Ksystemlog
      - brave-browser
      - teamviewer
      - zsh
      - flatpak

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: ~/.bashrc
      owner: filip
      group: filip

