---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: copy sources.list
    ansible.builtin.copy:
      src: files/sources.list
      dest: /etc/apt/sources.list
      owner: root
      group: root

  - name: Add brave browser repository key
    become: true
    shell: curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

  - name: copy brave repo file
    ansible.builtin.copy:
      src: files/brave-browser-release.list
      dest: /etc/apt/sources.list.d/brave-browser-release.list
      owner: filip
      group: filip

  - name: update system
    ansible.builtin.apt:
      update_cache: yes

  - name: install packages
    ansible.builtin.apt:
      pkg:
      - htop
      - curl
      - python3-psutil
      - qbittorrent
      - snapd
      - timeshift
      - ksystemlog
      - zsh
      - flatpak
      - nvidia-driver

  - name: copy .bashrc file
    ansible.builtin.copy:
      src: files/bashrc
      dest: /home/filip/.bashrc
      owner: filip
      group: filip

  - name: copy bashrc keybindings
    ansible.builtin.copy:
      src: files/inputrc
      dest: /etc/inputrc
      owner: root
      group: root

  - name: update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: install brave browser
    become: true
    ansible.builtin.apt:
      name: brave-browser
      state: present

  - name: install snap packages
    community.general.snap:
      name: "{{ item.name }}"
      classic: "{{ item.classic| default(false) }}"
      state: present
    loop:
      - name: whatsdesk
      - name: spotify
      - name: powershell
        classic: true
      - name: code
        classic: true

  - name: find all snap package desktop file
    become: true
    find:
      paths: /var/lib/snapd/desktop/applications/
      patterns: "*.desktop"
    register: snap_files

#  - name: copy snap package desktop files
#    become: true
#    fetch:
#      src: "{{ item.path }}"
#      dest: /usr/share/applications
#      owner: root
#      group: root
#    loop: "{{ snap_files.files }}"

#  - name: install vlc from flatpak
#    become_user: filip
#    flatpak:
#      name: org.videolan.VLC
#      method: user
#      state: present

  - name: remove pacages kalendarac # Cause of Kalendar Reminder process
    become: true
    ansible.builtin.package:
      loop: "{{ item  }}"
      state: absent
    loop:
      - kalendarac
      - kmail
      - kmailtransport-akonadi
      - korganizer
      - knotes
      - kdepim-themeeditors
      - libreoffice

  - name: Remove dependencies that are no longer required and purge their configuration files
    ansible.builtin.apt:
      autoremove: yes
      purge: true

  - name: install libreoffice from flatpak
    become: true
    ansible.builtin.flatpak:
      name: libreoffice
      state: present

  - name: remove firefox esr # Remove ESR before installing flatpak version
    become: true
    ansible.builtin.package:
      name: firefox-esr
      state: absent

  - name: install firefox from flatpak
    become_user: filip
    community.general.flatpak:
      name: org.mozilla.firefox
      state: present

  - name: download teamviewer
    ansible.builtin.get_url:
      url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
      dest: /home/filip/Downloads

  - name: install teamviewer
    become: true
    delegate_to: teamviewer
    apt:
      deb: /home/filip/Downloads/teamviewer_15.51.5_amd64.deb

  - name: configure plasma
    become: true
    copy:
      src: files/plasma-org.kde.plasma.desktop-appletsrc
      dest: /home/filip/.config/plasma-org.kde.plasma.desktop-appletsrc
      owner: filip
      group: filip

  - name: configure plasma
    become: true
    ansible.builtin.copy:
      src: files/kdeglobals
      dest: /home/filip/.config/kdeglobals
      owner: filip
      group: filip

  - name: configure plasma
    become: true
    ansible.builtin.copy:
      src: files/xsettingsd.conf
      dest: /home/filip/.config/xsettingsd/xsettingsd.conf
      owner: filip
      group: filip

  - name: create directory /home/filip/bin # Will be dest path for scripts
    ansible.builtin.file:
      path: /home/filip/bin
      state: directory

  - name: add update script
    ansible.builtin.copy:
      src: files/update.sh
      dest: /home/filip/bin/update.sh
      owner: filip
      group: filip

  - name: add nano config
    become: true
    ansible.builtin.copy:
      src: files/nanorc
      dest: /etc/nanorc
      owner: root
      group: root

  - name: add kwinrc - night colour
    become: true
    ansible.builtin.copy:
      src: files/kwinrc
      dest: /home/filip/.config/kwinrc
      owner: filip
      group: filip

  - name: add konsolerc
    become_user: filip
    ansible.builtin.copy:
      src: files/konsolerc
      dest: /home/filip/.config/konsolerc
      owner: filip
      group: filip

  - name: copy mimeapps.list
    ansible.builtin.copy:
      src: files/mimeapps.list
      dest: /home/filip/.config/mimeapps.list
      owner: filip
      group: filip
